### ISSUE TITLE
Serveur geoip chez scalingo

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/covid19_map#1]
J'utilise actuellement le serveur geoip que j'ai installé pour @indoorequal. 

Il faudrait déployer le même pour caresteouvert sur `geo.caresteouvert.fr`.

Il faut utiliser cette branche: https://github.com/francois2metz/geoapi/tree/update-geoip

**Comment by PanierAvide** [comment]
Quand tu as un domaine sur lequel pointer, j'ajoute le CNAME `geo.caresteouvert.fr`

**Comment by francois2metz** [comment]
Voila l'app sur laquelle il faut faire pointer le CNAME: `covid19-fr-geoip.osc-fr1.scalingo.io`.

**Comment by PanierAvide** [comment]
Ajouté au DNS

**Comment by francois2metz** [comment]
Hop, rajouté dans la config dc378be711d21c9abc6e213a7bdb597117076859.

Merci pour la mise à jour.
