### ISSUE TITLE
Mettre 3 priorités de bug, issue (low, medium, high), accessible aux gens qui remontent les bugs

### ISSUE THREAD

**Issue by vinber** [osmontrouge/covid19_map#11]

**Comment by PanierAvide** [comment]
J'ai ajouté les étiquettes, mais par contre je crois que celles-ci ne peuvent être appliquées que si l'on est collaborateur sur le dépôt (cf https://github.com/isaacs/github/issues/148 ). Je t'ai ajouté dans les personnes qui peuvent modifier les étiquettes ;-)

**Comment by vinber** [comment]
merci, mais je suis vraiment un boulet, je ne vois pas ce que cela change, je n'arrive pas à mettre un label low par exemple sur "on ne voit pas bien les icones"
j'ai tenté de me déconnecter et reconnecter, cela n'a rien changé

**Comment by vinber** [comment]
stop :) je n'avais pas vue l'invitation :)

**Comment by vinber** [comment]
donc juste merci !

**Comment by PanierAvide** [comment]
:smile:
