### ISSUE TITLE
Ajouter la page facebook dans les infos de contact

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/covid19_map#19]
Tags : facebook=* et contact:facebook=*

**Comment by vinber** [comment]
à mon avis pas avec un compte unique #13 
ajouter des nouveaux tags spécifiques ok, commencer à modifier, attention, on bascule sur d'autres problématiques (syntax, rempalcement, ...)

**Comment by overflorian** [comment]
Je ne suis pas certain de comprendre tes réticences.
On parle d'une URL vers une page facebook, c'est de l'info hyper structurée sans trop de possibilité de foirer, non ?

**Comment by vinber** [comment]
faire de l'édition derrière un compte générique, sur des données potentiellement existantes (donc tester l'existance ou pas ...) avant de l'inscrire me semble élargir beaucoup !

**Comment by francois2metz** [comment]
On parle de l'affichage ici simplement. Je pense que c'est raisonnable de supporter facebook.

**Comment by vinber** [comment]
pardon, mauvaise compréhension, je sors :)

**Comment by vinber** [comment]
confusion avec #18
