### ISSUE TITLE
Diminuer la taille des tuiles des POIs

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/covid19_map#2]
`pg_featureserv` nous renvoit tout les données de la table poi sans filtres. On récupère du coup tout les tags OSM alors que nous n'en avons pas besoin. Réduire la taille des tuiles améliore les perfs coté serveur et client.

Solutions envisagées:

- créer un vue avec juste les infos nécessaire
- utiliser un autre serveur de tuile vecto avec une requête qui va bien
- autre ?

**Comment by PanierAvide** [comment]
J'ai créé une vue `poi_osm_light` avec cette structure

```
                 View "public.poi_osm_light"
 Column |         Type         | Collation | Nullable | Default 
--------+----------------------+-----------+----------+---------
 fid    | character varying    |           |          | 
 geom   | geometry(Point,3857) |           |          | 
 name   | character varying    |           |          | 
 cat    | character varying    |           |          | 
 status | character varying    |           |          | 
```

Requête SQL
```sql
CREATE OR REPLACE VIEW poi_osm_light AS
SELECT fid, geom, name, cat, status
FROM poi_osm
WHERE status != 'fermé';
```

**Comment by francois2metz** [comment]
Ca m'a l'air très intéressant:

- https://tiles.caresteouvert.fr/public.poi_osm_light/13/4206/2922.pbf : 25kb transféré, taille: 53kb
- https://tiles.caresteouvert.fr/public.poi_osm/13/4206/2922.pbf : 60kb transféré, taille: 123kb

**Comment by francois2metz** [comment]
J'ai déployé avec cette nouvelle vue.
