### ISSUE TITLE
Redirect http -> https

### ISSUE THREAD

**Issue by Phyks** [osmontrouge/covid19_map#26]
De nombreux proxys et mécanismes de contrôle de connexions internet (administrations, entreprises etc) ont des règles assez strictes de filtrage et bloquent la version http. Envisager une redirection automatique http -> https ? (location 301)

**Comment by francois2metz** [comment]
C'est déjà le cas non ? http://www.caresteouvert.fr/ => https://www.caresteouvert.fr/

**Comment by vdct** [comment]
Ca fonctionne bien vu de chez moi

Le 26/03/2020 à 16:01, François de Metz a écrit :

**Comment by vinber** [comment]
cela marche aussi chez moi

**Comment by vinber** [comment]
@Phyks tu as vu ce souci à quel moment ?

**Comment by Phyks** [comment]
Ah oui, en effet... désolé pour le bruit.

Constaté sur mon poste pro, http://{www.,}caresteouvert.fr est bloqué mais pas la version https. Visiblement, il ne sait pas gérer les 301… Je ferme on peut probablement pas y faire grand chose.
