### ISSUE TITLE
Afficher tous les objets où opening_hours:covid19 est renseigné

### ISSUE THREAD

**Issue by charlesmillet** [osmontrouge/covid19_map#27]
Salut,
J'ai commencé à contribuer j'ai vu qu'il semblait manquer les shop=farm car la ferme où je vais n'est pas affichée. J'ai ajouté le opening_hours:covid19=same.
Bon courage :)

**Comment by PanierAvide** [comment]
Salut, à vrai dire tous les objets dont le tag `opening_hours:covid19` a été renseigné devraient être pris en compte. On va modifier ça ;-)

**Comment by PanierAvide** [comment]
Ça été implémenté dans 1c817b6 et ça va pas tarder à apparaître sur la carte, merci pour ton retour :-)
