### ISSUE TITLE
Demander le partage de géoloc à l'utilisateur

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/covid19_map#29]
... et en prendre compte pour centrer la carte.

C'est vraiment essentiel pour la première UX sur le site

**Comment by francois2metz** [comment]
C'est en place dans la toolbar

**Comment by overflorian** [comment]
Merci, j'adore ce que tu as fait ! Cliquer sur le bouton fonctionne bien, je pense qu'on peut garder ça.
Par contre le site ne demande pas encore le partage de la géoloc à l'ouverture (sans aucun clic). Je pense que c'est ce qu'il faut faire pour être certain d'afficher les alentours du logement de l'utilisateur.

**Comment by francois2metz** [comment]
La personne arrive, ne connait pas le site, mais directement on lui demande sa géolocalisation ?
Ce n'est pas l'expérience que j'ai envie d'offrir sur caresteouvert.

**Comment by overflorian** [comment]
Qu'en pensent @PanierAvide @vinber ?

**Comment by PanierAvide** [comment]
J'avoue que la géoloc direct ça a le don de m'agacer, mais je suis peut-être pas le public cible non plus :stuck_out_tongue_closed_eyes:

**Comment by vinber** [comment]
comme @PanierAvide j'ai tendance à désactiver directement.

**Comment by overflorian** [comment]
ok on oublie alors; merci :)
