### ISSUE TITLE
La licence

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/covid19_map#3]
Il nous faut une licence. 

Je propose l'AGPL v3. D'autres propositions ?

**Comment by PanierAvide** [comment]
C'est très bien, ce sera compatible avec les bouts de code de la base de données en place qui sont déjà sous cette licence. Si ça vous va je peux ajouter le fichier de licence et le lien dans le readme.

**Comment by vdct** [comment]
Impec 

----- Mail original -----

De: "Adrien Pavie" <notifications@github.com> 
À: "osmontrouge/covid19_map" <covid19_map@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 25 Mars 2020 16:25:16 
Objet: Re: [osmontrouge/covid19_map] La licence (#3) 






C'est très bien, ce sera compatible avec les bouts de code de la base de données en place qui sont déjà sous cette licence. Si ça vous va je peux ajouter le fichier de licence et le lien dans le readme.

**Comment by francois2metz** [comment]
:+1:
