### ISSUE TITLE
Ouvrir le volet de gauche par défaut

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/covid19_map#30]
lorsque l'on arrive sur le site; sinon il n'y a pas d'interface, c'est bloquant pour les débutants.

**Comment by francois2metz** [comment]
En quoi c'est bloquant ?

**Comment by vinber** [comment]
on est perdu :)

**Comment by overflorian** [comment]
pardon je n'ai pas été assez clair : lorsqu'un débutant / technophobe se connecte sur le site, il ne voit que la carte, pas d'interface. Impossible de savoir à quoi sert ce site ou quelle va être l'interaction possible. Si le volet de gauche se charge à l'ouverture, alors tout s'éclaire !

**Comment by PanierAvide** [comment]
J'ai réactivé la barre par défault sur PC, sur mobile on est d'accord qu'elle reste bien caché par défaut ?

**Comment by overflorian** [comment]
Pour l'instant oui mais je pense qu'il va falloir trouver à terme un moyen d'informer l'utilisateur de l'utilité du site.
Merci
