### ISSUE TITLE
Ça reste toujours ouvert ! Tenir compte des notes ?

### ISSUE THREAD

**Issue by Bibi56** [osmontrouge/covid19_map#37]
Banque Populaire, Guidel
était marqué : ouvert, privilégier le téléphone
En fait est fermé (les conseillers sont joignables,, certaines agences restent ouvertes pas celle-ci).
Je clique sur modifier, enregistrer... et on me dit que le POI est ouvert.
La note créée indique bien que c'est fermé : la règle globale https://github.com/PanierAvide/Covid_enseignes/blob/master/regles.csv semble être prioritaire.

https://www.openstreetmap.org/way/70436173
https://www.openstreetmap.org/note/2133179
https://www.caresteouvert.fr/@47.789208,-3.487083,17.00/place/w70436173

**Comment by francois2metz** [comment]
Bonjour,

Merci pour ce retour.

Il faut intégrer la note dans OSM et que l'on mette à jour les données. J'ai rajouté le tag dans OSM, et ça passera dans la prochaine mise à jour.

**Comment by PanierAvide** [comment]
Bonjour,

Effectivement pour prise en compte plus rapide, le mieux est de renseigner OpenStreetMap directement, sur la base des tags décrite ici : https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19

Les infos renseignées dans OSM sont bien prioritaires sur les règles définies dans covid_enseignes, c'est juste que l'on travaille encore à la mise à jour toutes les heures de la carte en ligne (promis ça arrive très bientôt) ;-)

Cordialement.

**Comment by PanierAvide** [comment]
Comme la base est désormais actualisée toutes les heures, la modification en question est bien effective sur la carte. Je ferme donc le ticket.
