### ISSUE TITLE
Valeur "ouvert"

### ISSUE THREAD

**Issue by gendy54** [osmontrouge/covid19_map#41]
Hello,

Pour les magasins ouverts mais où on a pas les horaires habituels, je propose une nouvelle valeur:
opening_hours:covid19=open
Sinon je ne sais pas quoi faire du commentaire comme quoi la pharmacie est ouverte mais sans plus.

Votre avis?

**Comment by PanierAvide** [comment]
Pour l'instant on était sur `opening_hours:covid19=same`, même s'il n'y a pas d'horaires renseignées de base c'est pas grave : on a indiqué que ce sont les mêmes que d'habitude.

**Comment by gendy54** [comment]
OK j'avais pas vu ca comme ca, mais les explications me vont.
