### ISSUE TITLE
textarea pour entrer les précisions peu visible

### ISSUE THREAD

**Issue by zorun** [osmontrouge/covid19_map#44]
La première fois que j'ai voulu signaler un changement, sur mobile, je n'ai pas vu le textarea où j'étais censé mettre des précisions...

Sur PC c'est un peu mieux parce que le curseur de souris change, mais le textarea reste peu visible. Sur mobile il n'y a pas de curseur qui donne une indication...

Ça doit venir du fait qu'il n'y a pas de bordure, du coup on se dit que c'est une zone blanche sans aucun élément.

**Comment by PanierAvide** [comment]
Merci de ce retour, ça a été corrigé et ce sera bientôt disponible en ligne.

**Comment by zorun** [comment]
Super, merci de la réactivité !
