### ISSUE TITLE
On ne lit pas bien la consigne

### ISSUE THREAD

**Issue by vinber** [osmontrouge/covid19_map#5]
![Capture d’écran de 2020-03-25 19-52-21](https://user-images.githubusercontent.com/890869/77574431-44855e00-6ed2-11ea-9b1c-b03799d64ffd.png)

**Comment by francois2metz** [comment]
Merci d'avoir reporté ce problème. J'ai corrigé cela: 
![Screenshot_2020-03-26 Ça reste ouvert](https://user-images.githubusercontent.com/86659/77596879-88418d00-6efd-11ea-9ea6-10a86db945b4.png)
